### ISSUE TITLE
idraw.__getOriginContext2D is not a function

### ISSUE THREAD

**Issue by gtnl** [idrawjs/studio#39]
菜鸟一个，下载安装后，点界面顶端的下载图片按钮报错：
react-dom.development.js:22839 Uncaught TypeError: idraw.__getOriginContext2D is not a function
    at toDataURL (file.js:38:23)
    at iDraw.toDataURL (index.js:42:16)
    at export-image.tsx:58:23
    at export-image.tsx:63:5
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:7)
    at commitPassiveMountEffects (react-dom.development.js:24866:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:3)

**Comment by chenshenhai** [comment]
目前已升级到 v0.4.0 版本，不存在该feature及其错误
